### ISSUE TITLE
[Question] Device Information

### ISSUE THREAD

**Issue by SteffenGorenflo** [locator-kn/ios-app#2]
We need device information of each device in backend. What kind of information can you provide?

We need (at least) the following:
-  An ID to identify the device
-  A push ID, used for sending push notifications to the device

**Comment by michaelknoch** [comment]
we could provide both of them. What could additionally be interesting for you?

**Comment by timoweiss** [comment]
show us what you got :santa:

**Comment by michaelknoch** [comment]
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIDevice_Class/#//apple_ref/doc/uid/TP40006902-CH3-SW9
- name
- systemName
- systemVersion
- model
- localizedModel
- userInterfaceIdiom
- identifierForVendor
- UIDeviceBatteryState
- UIDeviceOrientation
- UIUserInterfaceIdiom

**Comment by SteffenGorenflo** [comment]
``` js
{
 deviceId: the device identifier,
 type: ios or android,
 version: version of your OS,
 deviceModel: e.g. Galaxy S3 or iPhone 6
}
```
