### ISSUE TITLE
ui feedback

### ISSUE THREAD

**Issue by tschulo** [locator-kn/ios-app#28]
ist des so ok?
bei fragen - fragen :) 

![feedback_bubblescreen](https://cloud.githubusercontent.com/assets/12935497/13547538/fb35ffb4-e2d7-11e5-84ef-ab4449869b7c.jpg)
![feedback_foto gemacht](https://cloud.githubusercontent.com/assets/12935497/13547539/fb38c1fe-e2d7-11e5-8134-77d0d9b58c34.jpg)
![feedback_kategorien](https://cloud.githubusercontent.com/assets/12935497/13547541/fb3d5822-e2d7-11e5-88f4-af6e7170e5b7.jpg)
![feedback_locationdetail](https://cloud.githubusercontent.com/assets/12935497/13547543/fb403aec-e2d7-11e5-9d2a-4f94ff48b4cb.jpg)
![feedback_profil](https://cloud.githubusercontent.com/assets/12935497/13547540/fb3bb486-e2d7-11e5-98a1-b60744499ec8.jpg)

**Comment by michaelknoch** [comment]
done
