### ISSUE TITLE
LogIn after LogOut

### ISSUE THREAD

**Issue by andmaier** [locator-kn/ios-app#34]
After logging out you can't log yourself in anymore... all it says is that your login-data is wrong

**Comment by michaelknoch** [comment]
cant reproduce, works for me.
Did you use an existing account or have you registered a new one?

**Comment by andmaier** [comment]
logged in this morning with existing account from v.1. (with generated password from 'cant-remember-password' function) after logging out and reopening the app it says my data is wrong. after reinstalling the app I can log in again

**Comment by michaelknoch** [comment]
moved to [cor/#107](https://github.com/locator-kn/cor/issues/107)
