### ISSUE TITLE
implement mixpanel events

### ISSUE THREAD

**Issue by michaelknoch** [locator-kn/ios-app#42]
Which events should be tracked and how should they be named?
- App | auto login success
- App | proceed as guest
- App | login
- App | register
- App | FB login
- App | Logout
- App | launch
- App | become inactive
- Userview | load
- Userview | follow
- Userview | unfollow
- Locationview | load
- Locationview | like
- Locationview | unlike
- Locationview | show on map
- Locationview | user click
- Locationview | textimpression success
- Locationview | videoimpression success
- Locationview | imageimpression success
- Bubble | schönhier
- Bubble | map click
- Bubble | map swipe
- Bubble | refresh click
- Bubble | shake
- Bubble | open my locator
- Bubble | location click
- Map | schönhier
- Map | location create

**Comment by markusheilig** [comment]
thank u @michaelknoch for this long list.
i think those points should be enough for the beginning.

should we also use the tracking system for failure tracking? i.e. "could not receive /my/bubblescreen" or something like that?

**Comment by michaelknoch** [comment]
thought about this too, but we should keep this as simple as possible and so i would leave error tracking as a backend task? @SteffenGorenflo what do you think?

**Comment by SteffenGorenflo** [comment]
yep backend task. We already have logging files and we can use them

**Comment by michaelknoch** [comment]
updated strings "/" --> "|"
